[pytest]
python_files = test*.py
; markers =
;     positive_test: только позитивные тесты
; python_functions = test_sum_positive_nums
; python_functions = text_verific
markers =
    positive: Тесты, которые проверяют корректное поведение функции
    negative: Тесты, которые проверяют некорректное поведение функции